# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda12408382685638e799f995a49f040cbf20a14965b5768ad6473fe86c51f692d9ddfdcbfd2c08e460e2f3e1a47a8e76bdd5a64a59e06165adbc8791710829f

test:
  secret_key_base: abcdfee7866b21f991c114c892dfa3272b8750455901692b323f405be94a4c8b75f7aff20a7b5301c96f57953847ade785bc3a38e6491fc70ed72eb891d251db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
